/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.evolutionnext.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Artist extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3343594464687316523L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Artist\",\"namespace\":\"com.evolutionnext.avro\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"alias\",\"type\":[\"string\",\"null\"]},{\"name\":\"albums\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Album\",\"fields\":[{\"name\":\"name\",\"type\":\"string\"},{\"name\":\"yearReleased\",\"type\":[\"int\",\"null\"]}]}},\"doc\":\"All the albums recorded by this artist\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Artist> ENCODER =
      new BinaryMessageEncoder<Artist>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Artist> DECODER =
      new BinaryMessageDecoder<Artist>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Artist> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Artist> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Artist>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Artist to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Artist from a ByteBuffer. */
  public static Artist fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence name;
  @Deprecated public java.lang.CharSequence alias;
  /** All the albums recorded by this artist */
  @Deprecated public java.util.List<com.evolutionnext.avro.Album> albums;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Artist() {}

  /**
   * All-args constructor.
   * @param name The new value for name
   * @param alias The new value for alias
   * @param albums All the albums recorded by this artist
   */
  public Artist(java.lang.CharSequence name, java.lang.CharSequence alias, java.util.List<com.evolutionnext.avro.Album> albums) {
    this.name = name;
    this.alias = alias;
    this.albums = albums;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return name;
    case 1: return alias;
    case 2: return albums;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: name = (java.lang.CharSequence)value$; break;
    case 1: alias = (java.lang.CharSequence)value$; break;
    case 2: albums = (java.util.List<com.evolutionnext.avro.Album>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'alias' field.
   * @return The value of the 'alias' field.
   */
  public java.lang.CharSequence getAlias() {
    return alias;
  }

  /**
   * Sets the value of the 'alias' field.
   * @param value the value to set.
   */
  public void setAlias(java.lang.CharSequence value) {
    this.alias = value;
  }

  /**
   * Gets the value of the 'albums' field.
   * @return All the albums recorded by this artist
   */
  public java.util.List<com.evolutionnext.avro.Album> getAlbums() {
    return albums;
  }

  /**
   * Sets the value of the 'albums' field.
   * All the albums recorded by this artist
   * @param value the value to set.
   */
  public void setAlbums(java.util.List<com.evolutionnext.avro.Album> value) {
    this.albums = value;
  }

  /**
   * Creates a new Artist RecordBuilder.
   * @return A new Artist RecordBuilder
   */
  public static com.evolutionnext.avro.Artist.Builder newBuilder() {
    return new com.evolutionnext.avro.Artist.Builder();
  }

  /**
   * Creates a new Artist RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Artist RecordBuilder
   */
  public static com.evolutionnext.avro.Artist.Builder newBuilder(com.evolutionnext.avro.Artist.Builder other) {
    return new com.evolutionnext.avro.Artist.Builder(other);
  }

  /**
   * Creates a new Artist RecordBuilder by copying an existing Artist instance.
   * @param other The existing instance to copy.
   * @return A new Artist RecordBuilder
   */
  public static com.evolutionnext.avro.Artist.Builder newBuilder(com.evolutionnext.avro.Artist other) {
    return new com.evolutionnext.avro.Artist.Builder(other);
  }

  /**
   * RecordBuilder for Artist instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Artist>
    implements org.apache.avro.data.RecordBuilder<Artist> {

    private java.lang.CharSequence name;
    private java.lang.CharSequence alias;
    /** All the albums recorded by this artist */
    private java.util.List<com.evolutionnext.avro.Album> albums;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.evolutionnext.avro.Artist.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.alias)) {
        this.alias = data().deepCopy(fields()[1].schema(), other.alias);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.albums)) {
        this.albums = data().deepCopy(fields()[2].schema(), other.albums);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Artist instance
     * @param other The existing instance to copy.
     */
    private Builder(com.evolutionnext.avro.Artist other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.name)) {
        this.name = data().deepCopy(fields()[0].schema(), other.name);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.alias)) {
        this.alias = data().deepCopy(fields()[1].schema(), other.alias);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.albums)) {
        this.albums = data().deepCopy(fields()[2].schema(), other.albums);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.evolutionnext.avro.Artist.Builder setName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.name = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.evolutionnext.avro.Artist.Builder clearName() {
      name = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'alias' field.
      * @return The value.
      */
    public java.lang.CharSequence getAlias() {
      return alias;
    }

    /**
      * Sets the value of the 'alias' field.
      * @param value The value of 'alias'.
      * @return This builder.
      */
    public com.evolutionnext.avro.Artist.Builder setAlias(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.alias = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'alias' field has been set.
      * @return True if the 'alias' field has been set, false otherwise.
      */
    public boolean hasAlias() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'alias' field.
      * @return This builder.
      */
    public com.evolutionnext.avro.Artist.Builder clearAlias() {
      alias = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'albums' field.
      * All the albums recorded by this artist
      * @return The value.
      */
    public java.util.List<com.evolutionnext.avro.Album> getAlbums() {
      return albums;
    }

    /**
      * Sets the value of the 'albums' field.
      * All the albums recorded by this artist
      * @param value The value of 'albums'.
      * @return This builder.
      */
    public com.evolutionnext.avro.Artist.Builder setAlbums(java.util.List<com.evolutionnext.avro.Album> value) {
      validate(fields()[2], value);
      this.albums = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'albums' field has been set.
      * All the albums recorded by this artist
      * @return True if the 'albums' field has been set, false otherwise.
      */
    public boolean hasAlbums() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'albums' field.
      * All the albums recorded by this artist
      * @return This builder.
      */
    public com.evolutionnext.avro.Artist.Builder clearAlbums() {
      albums = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Artist build() {
      try {
        Artist record = new Artist();
        record.name = fieldSetFlags()[0] ? this.name : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.alias = fieldSetFlags()[1] ? this.alias : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.albums = fieldSetFlags()[2] ? this.albums : (java.util.List<com.evolutionnext.avro.Album>) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Artist>
    WRITER$ = (org.apache.avro.io.DatumWriter<Artist>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Artist>
    READER$ = (org.apache.avro.io.DatumReader<Artist>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
